version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:5000']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  kibana:
    build:
      context: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm_server:
    build:
      context: apm/
    container_name: apm
    volumes:
      - ./apm/config/:/usr/share/apm/config:ro
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch  

volumes:
  elastic_data:
    driver: local

networks:
  elk:
    driver: bridge
