version: "3.8"

services: 
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        volumes: 
            - mongo-data:/data/db
        ports: 
            - 27017:27017
    redis:
        container_name: redis
        image: redis:6
        ports:
            - 6379:6379
        volumes:
            - redis_data:/bitnami/redis/data
    postgres:
        container_name: postgres
        image: postgres:13
        environment: 
            POSTGRES_PASSWORD: postgres
            # POSTGRES_USER: unicorn_user
            # POSTGRES_PASSWORD: magical_password
            # POSTGRES_DB: rainbow_database
        ports: 
            - 5432:5432
        volumes: 
            - postgres_data:/var/lib/postgresql/data
    zookeeper-server:
        container_name: zookeeper
        image: 'bitnami/zookeeper:latest'
        networks:
            - kafka-net
        ports:
            - '2181:2181'
        volumes: 
            - zookeeper_data:/bitnami/zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka-server1:
        container_name: kafka1
        image: 'bitnami/kafka:latest'
        networks:
            - kafka-net    
        ports:
            - '9092:9092'
        volumes: 
            - kafka1_data:/bitnami/kafka
        environment:
            # - KAFKA_CFG_BROKER_ID=0
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper-server
    # kafka-server2:
    #     container_name: kafka2
    #     image: 'bitnami/kafka:latest'
    #     networks:
    #         - kafka-net    
    #     ports:
    #         - '9093:9092'
    #     volumes: 
    #         - kafka2_data:/bitnami/kafka
    #     environment:
    #         - KAFKA_CFG_BROKER_ID=1
    #         - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    #         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on:
    #         - zookeeper-server

volumes: 
    mongo-data:
    redis_data:
        driver: local
    postgres_data:
    zookeeper_data:
    kafka1_data:
    # kafka2_data:

networks:
    kafka-net:
        driver: bridge